export enum NoteDuration {
  Whole = 1,
  Half = 1 / 2,
  Quarter = 1 / 4,
  Eighth = 1 / 8,
  Sixteenth = 1 / 16,
  ThirtySecond = 1 / 32,
  SixtyFourth = 1 / 64,
  HalfDotted = 1 / 2 + 1 / 4,
  QuarterDotted = 1 / 4 + 1 / 8,
  EighthDotted = 1 / 8 + 1 / 16,
  SixteenthDotted = 1 / 16 + 1 / 32,
  ThirtySecondDotted = 1 / 32 + 1 / 64,
  SixtyFourthDotted = 1 / 64 + 1 / 128,
  HalfDoubleDotted = 1 / 2 + 1 / 4 + 1 / 8,
  QuarterDoubleDotted = 1 / 4 + 1 / 8 + 1 / 16,
  EighthDoubleDotted = 1 / 8 + 1 / 16 + 1 / 32,
  SixteenthDoubleDotted = 1 / 16 + 1 / 32 + 1 / 64,
  ThirtySecondDoubleDotted = 1 / 32 + 1 / 64 + 1 / 128,
  SixtyFourthDoubleDotted = 1 / 64 + 1 / 128 + 1 / 256,
  HalfTriplet = (1 / 1) * (1 / 3),
  QuarterTriplet = (1 / 2) * (1 / 3),
  EighthTriplet = (1 / 4) * (1 / 3),
  SixteenthTriplet = (1 / 8) * (1 / 3),
  ThirtySecondTriplet = (1 / 32) * (1 / 3),
  SixtyFourthTriplet = (1 / 64) * (1 / 3),
}

export const DURATION_TO_NAME = {
  [NoteDuration.Whole]: "1",
  [NoteDuration.Half]: "2",
  [NoteDuration.Quarter]: "4",
  [NoteDuration.Eighth]: "8",
  [NoteDuration.Sixteenth]: "16",
  [NoteDuration.ThirtySecond]: "32",
  [NoteDuration.SixtyFourth]: "64",
  [NoteDuration.HalfDotted]: "2d",
  [NoteDuration.QuarterDotted]: "4d",
  [NoteDuration.EighthDotted]: "8d",
  [NoteDuration.SixteenthDotted]: "16d",
  [NoteDuration.ThirtySecondDotted]: "32d",
  [NoteDuration.SixtyFourthDotted]: "64d",
  [NoteDuration.HalfDoubleDotted]: "2dd",
  [NoteDuration.QuarterDoubleDotted]: "4dd",
  [NoteDuration.EighthDoubleDotted]: "8dd",
  [NoteDuration.SixteenthDoubleDotted]: "16dd",
  [NoteDuration.ThirtySecondDoubleDotted]: "32dd",
  [NoteDuration.SixtyFourthDoubleDotted]: "64dd",
  [NoteDuration.HalfTriplet]: "2t",
  [NoteDuration.QuarterTriplet]: "4t",
  [NoteDuration.EighthTriplet]: "8t",
  [NoteDuration.SixteenthTriplet]: "16t",
  [NoteDuration.ThirtySecondTriplet]: "32t",
  [NoteDuration.SixtyFourthTriplet]: "64t",
};
